[meta]
version = "0.1.0"

[project]
name = "xltransport_py"
package = "xltransport_py"
main_lang = "py"
version = "0.0.11"
version_date = "2018-03-04"
author = "Jim Dixon"
author_email = "jddixon@gmail.com"
copyright = "2017"
description = "transport layer for xlattice_py"
dev_status = "pre_alpha"
license = "mit"
relpath = "py/xltransport_py"
state = "shared"
url = "https://jddixon.github.io/xltransport_py"

[py]
packages = [ "xltransport",]
package_dir = [ "src",]
test_dir = [ "tests",]
py_modules = []
scripts = []
ext_modules = []
distshare = [ "rnglib",]
env_vars = []
requirements = [ "setuptools",]
test_requirements = []
